// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS663aoxmdv77sRCYiSqQUVfV44BtxY-4',
    appId: '1:271452705878:web:811282526837082e8c17f7',
    messagingSenderId: '271452705878',
    projectId: 'gram-sanjog',
    authDomain: 'gram-sanjog.firebaseapp.com',
    storageBucket: 'gram-sanjog.firebasestorage.app',
    measurementId: 'G-4DPCF3YSNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmXn8jGX8lH9F4QCKLaxQrCk5t-d3zROI',
    appId: '1:271452705878:android:1aac2741d969f8948c17f7',
    messagingSenderId: '271452705878',
    projectId: 'gram-sanjog',
    storageBucket: 'gram-sanjog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnJjX0SkwQ5MUGy1MvcnLcdHVAbq2Fs94',
    appId: '1:271452705878:ios:c09dd2084e4aaf798c17f7',
    messagingSenderId: '271452705878',
    projectId: 'gram-sanjog',
    storageBucket: 'gram-sanjog.firebasestorage.app',
    iosBundleId: 'com.example.gramSanjog',
  );
}
